title: Kai-Chih Tseng # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral at <a href="https://aos.princeton.edu/">Princeton University</a>
  <br><br>  
  <a href="https://www.dropbox.com/s/d5kac8165j73ous/cv.pdf?dl=0">CV</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
